services:
  # TODO: add client front-end

  service:
    image: webinator:latest
    depends_on:
      - db
    restart: always
    ports:
     - 5000:5000

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - ./__var__/pg:/var/lib/postgresql/data
    healthcheck:
        test: ["CMD-SHELL", "pg_isready"]
        interval: 30s
        timeout: 5s
        retries: 5
    ports:
      - "${DB_PORT}:${DB_PORT}"

  admin:
    container_name: pgadmin
    image: dpage/pgadmin4
    depends_on:
      - db
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${DB_ADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${DB_ADMIN_PASS}
    ports:
      - "5050:80"
